AWAITING_CHANNEL = "awaiting_channel"
AWAITING_BROADCAST = "awaiting_broadcast"
AWAITING_SUPPORT_MSG = "awaiting_support_msg"
AWAITING_ADMIN_REPLY = "awaiting_admin_reply"
AWAITING_PRIVACY_URL = "awaiting_privacy_url"
AWAITING_TERMS_URL = "awaiting_terms_url"
